In [3]:
import numpy as np
a=np.arange(12).reshape(3,4)**2
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [5]:
print(a[1:3])

[[ 16  25  36  49]
 [ 64  81 100 121]]


In [7]:
print(a[:1,2])

[4]


In [12]:
a=np.arange(12).reshape(3,4)
print(a)++

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
print(a[2
  :0,1])

[]


In [20]:
b=np.array([[1,2,3],[6,5,7],[8,9,5]])
print(b)

[[1 2 3]
 [6 5 7]
 [8 9 5]]


In [23]:
for i in a:
     print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [24]:
for i in a.flat:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
