<a href="https://colab.research.google.com/github/19PA1A0437ASHOK/AI/blob/master/yadav.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.arange(12).reshape(3,4)**2
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [0]:
print(a[1:3])

[[ 16  25  36  49]
 [ 64  81 100 121]]


In [0]:
print(a[:1,2])

[4]


In [0]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
print(a[0:1])

[[0 1 2 3]]


In [0]:
b=np.array([[1,2,3],[6,5,7],[8,9,5]])
print(b)

[[1 2 3]
 [6 5 7]
 [8 9 5]]


In [0]:
for i in a:
     print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [0]:
for i in a.flat:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
